FROM php:fpm-alpine

MAINTAINER Konstantin Grachev <ko@grachev.io>

ENV APP_DIR /usr/local/app

ENV COMPOSER_BIN_DIR /usr/local/bin
ENV COMPOSER_CACHE_DIR /var/cache/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

ENV PATH ${APP_DIR}/bin:${PATH}

WORKDIR ${APP_DIR}

RUN set -ex \
    && apk --no-cache add \
        git \
        icu-dev \
        zlib-dev \
    && docker-php-ext-install zip intl pdo_mysql iconv opcache \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer global require phpunit/phpunit

RUN apk add --no-cache --virtual .build-deps git openssh-client mysql-client $PHPIZE_DEPS \
    && pecl install xdebug \
    && echo 'zend_extension=xdebug.so' > /usr/local/etc/php/conf.d/xdebug.conf \
    && { \
        echo 'xdebug.remote_enable=On'; \
        echo 'xdebug.remote_autostart=On'; \
        echo 'xdebug.remote_connect_back=On'; \
    } >> ${PHP_INI_DIR}/conf.d/xdebug.ini \
    && apk del .build-deps

RUN set -ex \
    && { \
        echo '#!/bin/sh'; \
        echo 'set -e'; \
        echo 'while ! nc -z mysql 3306; do sleep 1; done'; \
        echo 'composer run-script build-parameters'; \
        echo 'php bin/console server:run 0.0.0.0:80'; \
    } > /usr/local/bin/docker-entrypoint.sh \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

CMD ["docker-entrypoint.sh"]
